import {
  Carrot,
  Beef,
  Fish,
  Wheat,
  Banana,
  Ham,
  Drumstick,
  Soup,
  UtensilsCrossed,
  Sandwich,
  Shell,
  Waves,
  Leaf,
  Sprout,
  ShoppingBasket,
  type LucideIcon,
} from "lucide-react";

/**
 * Maps a product category to a lucide icon. Falls back to a generic
 * basket icon for anything not explicitly listed, so adding a new
 * category never results in a blank spot.
 */
const categoryIconMap: Record<string, LucideIcon> = {
  Vegetables: Carrot,
  "Leafy Vegetables": Leaf,
  "Root Vegetables": Sprout,
  Fruits: Banana,
  "Rice & Grains": Wheat,
  Pork: Ham,
  Chicken: Drumstick,
  Beef: Beef,
  "Pork Organ Meats": Soup,
  "Chicken Organ Meats": Soup,
  "Beef Organ Meats": Soup,
  "Other Meat": UtensilsCrossed,
  "Processed Meat": Sandwich,
  Fish: Fish,
  "Dried Seafood": Fish,
  Shellfish: Shell,
  Seafood: Waves,
};

export function getCategoryIcon(category: string): LucideIcon {
  return categoryIconMap[category] ?? ShoppingBasket;
}

/**
 * Maps a specific item name to an emoji. Checked before the category
 * fallback so visually distinct items (e.g. Garlic vs Tomato) don't
 * all render the same icon just because they share a category.
 */
const itemEmojiMap: Record<string, string> = {
  Tomato: "🍅",
  "Red Onion": "🧅",
  "White Onion": "🧅",
  Garlic: "🧄",
  Ginger: "🫚",
  "Spring Onion": "🌱",
  Leek: "🧅",
  Celery: "🥬",
  "Lemongrass (Tanglad)": "🌿",
  "Cilantro (Wansoy)": "🌿",
  "Eggplant (Talong)": "🍆",
  "Bitter Melon (Ampalaya)": "🥒",
  Okra: "🌿",
  "String Beans (Sitaw)": "🫘",
  "Winged Beans (Sigarilyas)": "🫘",
  "Snow Peas (Sitsaro)": "🫛",
  "Green Beans": "🫘",
  "Chayote (Sayote)": "🥒",
  "Bottle Gourd (Upo)": "🥒",
  "Ridge Gourd (Patola)": "🥒",
  "Squash (Kalabasa)": "🎃",
  Cucumber: "🥒",
  "Pickling Cucumber": "🥒",
  "Green Bell Pepper": "🫑",
  "Red Bell Pepper": "🫑",
  "Green Chili (Siling Haba)": "🌶️",
  "Birds Eye Chili (Siling Labuyo)": "🌶️",
  "Young Corn": "🌽",
  "Bamboo Shoots (Labong)": "🎍",
  Cauliflower: "🥦",
  Broccoli: "🥦",
  Mushroom: "🍄",
  "Bean Sprouts (Togue)": "🌱",
  "Green Peas": "🫛",
  Corn: "🌽",
  "Corn on the Cob": "🌽",
  "Baguio Beans": "🫘",
  Potato: "🥔",
  "Sweet Potato (Kamote)": "🍠",
  "Cassava (Kamoteng Kahoy)": "🥔",
  "Taro (Gabi)": "🥔",
  Carrot: "🥕",
  "Radish (Labanos)": "🥕",
  "Turnip (Singkamas)": "🥕",
  Beetroot: "🥔",
  "Lotus Root": "🪷",
  Kangkong: "🥬",
  Pechay: "🥬",
  "Chinese Pechay": "🥬",
  "Mustard Greens (Mustasa)": "🥬",
  Cabbage: "🥬",
  Lettuce: "🥬",
  Spinach: "🥬",
  "Sweet Potato Leaves (Talbos ng Kamote)": "🥬",
  "Malunggay Leaves": "🌿",
  Alugbati: "🥬",
  Saluyot: "🥬",
  "Banana Blossom (Puso ng Saging)": "🌺",
  "Banana (Lakatan)": "🍌",
  "Well-Milled Rice": "🌾",
  "Whole Chicken": "🍗",
  "Chicken Breast": "🍗",
  "Chicken Thigh": "🍗",
  "Chicken Leg Quarter": "🍗",
  "Chicken Wings": "🍗",
  "Chicken Drumsticks": "🍗",
  "Chicken Neck": "🍗",
  "Chicken Feet (Adidas)": "🐔",
  "Chicken Skin": "🍗",
  "Chicken Intestines (Isaw)": "🍢",
  "Chicken Liver": "🍲",
  "Chicken Gizzard": "🍲",
  "Chicken Heart": "🍲",
  "Pork Belly (Liempo)": "🥓",
  "Pork Shoulder (Kasim)": "🥩",
  "Pork Leg (Pigue)": "🥩",
  "Pork Chop": "🥩",
  "Pork Ribs": "🍖",
  "Pork Loin": "🥩",
  "Ground Pork (Giniling)": "🥩",
  "Pork Cubes": "🥩",
  "Pork Bones (Buto-Buto)": "🦴",
  "Pork Hock (Pata)": "🍖",
  "Pork Head (Ulo)": "🐷",
  "Pork Ears": "🐷",
  "Pork Intestines (Isaw)": "🍢",
  "Pork Liver": "🍲",
  "Pork Heart": "🍲",
  "Pork Tongue": "🍲",
  "Pork Blood": "🩸",
  "Beef Sirloin": "🥩",
  "Beef Tenderloin": "🥩",
  "Beef Short Ribs": "🍖",
  "Beef Shank (Bulalo)": "🍖",
  "Beef Brisket": "🥩",
  "Beef Chuck": "🥩",
  "Ground Beef": "🥩",
  "Beef Cubes": "🥩",
  "Beef Bones": "🦴",
  "Beef Oxtail": "🍖",
  "Beef Liver": "🍲",
  "Beef Tripe (Goto)": "🍲",
  "Beef Tendon": "🍲",
  "Goat Meat (Kambing)": "🐐",
  "Carabao Meat": "🐃",
  Lamb: "🐑",
  Longganisa: "🌭",
  Tocino: "🥓",
  Hotdog: "🌭",
  Bacon: "🥓",
  Ham: "🍖",
  Meatloaf: "🥫",
  Chorizo: "🌭",
  Embutido: "🍖",
  Siomai: "🥟",
  "Chicken Nuggets": "🍗",
  "Burger Patties": "🍔",
  Bangus: "🐟",
  Tilapia: "🐟",
  Tamban: "🐟",
  Salmon: "🐟",
  Tuna: "🐟",
  Mackerel: "🐟",
  "Red Snapper (Maya-Maya)": "🐟",
  "Milkfish Belly": "🐟",
  "Boneless Bangus": "🐟",
  "Dalagang Bukid": "🐟",
  "Salay-Salay": "🐟",
  Dilis: "🐟",
  Galunggong: "🐟",
  "Dried Fish (Tuyo)": "🐠",
  "Dried Fish (Daing)": "🐠",
  "Dried Anchovies (Dilis)": "🐠",
  "Shrimp (Hipon)": "🦐",
  "Mussels (Tahong)": "🦪",
  "Clams (Halaan)": "🦪",
  "Oysters (Talaba)": "🦪",
  "Crab (Alimango)": "🦀",
  "Squid (Pusit)": "🦑",
  Seaweed: "🌊",
};

/** Fallback emoji per category, used when item name isn't in the map above. */
const categoryEmojiMap: Record<string, string> = {
  Vegetables: "🥦",
  "Leafy Vegetables": "🥬",
  "Root Vegetables": "🥕",
  Fruits: "🍎",
  "Rice & Grains": "🌾",
  Pork: "🥓",
  Chicken: "🍗",
  Beef: "🥩",
  "Pork Organ Meats": "🍲",
  "Chicken Organ Meats": "🍲",
  "Beef Organ Meats": "🍲",
  "Other Meat": "🍖",
  "Processed Meat": "🌭",
  Fish: "🐟",
  "Dried Seafood": "🐠",
  Shellfish: "🦪",
  Seafood: "🌊",
};

export function getItemEmoji(itemName: string, category: string): string {
  return itemEmojiMap[itemName] ?? categoryEmojiMap[category] ?? "🧺";
}